dist: trusty
os:
- linux
- osx
language: c
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq pkg-config zip g++ zlib1g-dev unzip python openjdk-8-jdk bazel ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap bazelbuild/tap && brew tap-pin bazelbuild/tap; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bazel ; fi
- mkdir -p "$HOME/.cache/bazel/"
- bazel version
- echo "build --conlyopt=-std=c99 --compilation_mode=opt" > $HOME/.bazelrc
- echo "build --disk_cache=$HOME/.cache/bazel/" >> $HOME/.bazelrc
- echo "build --announce_rc" >> $HOME/.bazelrc
script:
- bazel test //ryu/... //src/...
- bazel run //ryu/benchmark
- bazel test --copt=-DRYU_ONLY_64_BIT_OPS //ryu/...
- bazel run --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark
- bazel test --copt=-DRYU_OPTIMIZE_SIZE //ryu/... //src/...
- bazel run --copt=-DRYU_OPTIMIZE_SIZE //ryu/benchmark
- bazel test --copt=-DRYU_OPTIMIZE_SIZE --copt=-DRYU_ONLY_64_BIT_OPS //ryu/...
- bazel run --copt=-DRYU_OPTIMIZE_SIZE --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark
