name = "ryu"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Ryu"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[lean_lib]]
name = "Ryu"
srcDir = "lean"